variable "subscription_id" {}
variable "tenant_id" {}
variable "client_id" {}  
variable "client_secret" {}
variable "location" {}
variable "resource_group_name" {}
variable "key_vault_name" {}
variable "key_vault_sku_name" {}
variable "key_vault_key_name" {}
variable "disk_encryption_set_name" {}
variable "data_disk_name" {}
variable "data_disk_size_gb" {}
variable "data_disk_storage_type" {}
variable "data_disk_creation_option" {}
