name: Terraform-Workflow
on: workflow_dispatch
jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.TF_VAR_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.TF_VAR_CLIENT_SECRET }}
          
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.10.3
            
            - name: Initializing Terraform
              run: terraform init

            - name: Terraform Plan
              run: terraform plan -out=tfplan