name: Terraform-Workflow
on: workflow_dispatch
jobs:
    Terraform-Apply-Job:
        runs-on: ubuntu-latest
        env:
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_TENANT_ID }}
          TF_VAR_client_id: ${{ secrets.TF_VAR_CLIENT_ID }}
          TF_VAR_client_secret: ${{ secrets.TF_VAR_CLIENT_SECRET }}
          
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.10.3
            
            - name: Initializing Terraform
              run: terraform init

            - name: Terraform Plan
              run: terraform plan -out=tfplan
            
            - name: Terraform Apply
              id: terraform-apply
              run: terraform apply -auto-approve tfplan

            - name: Upload terraform state file
              if: success() && steps.terraform-apply.outcome == 'success'
              uses: actions/upload-artifact@v4
              with:
                  name: terraform-state-file
                  path: terraform.tfstate
            
            - name: Terraform Destroy
              if: failure() && steps.terraform-apply.outcome == 'failure'
              run: terraform destroy -auto-approve
            
            - name: listing the files in current directory
              if: always()
              run: ls -al
